### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by seanbaxter** [nvpro-samples/glsl_indexed_types_generator#2]
$ glslc --target-spv=spv1.0 -fshader-stage=frag test.frag.glsl -o frag.spv
$ spirv-val frag.spv
error: line 252: Result <id> from OpSampledImage instruction must not appear as operand for OpReturnValue, since it is not specificed as taking an OpTypeSampledImage. Found result <id> '66[%66]' as an operand of <id> '0[%0]'.
  %66 = OpSampledImage %13 %64 %65

Are my tools out of date?
shaderc v2020.5-dev v2020.4-1-g4089217
spirv-tools v2020.7-dev v2020.6-14-g17ffa890
glslang 8.13.3743-225-g517f39ee

**Comment by Ipotrick** [comment]
This whole thing seems to be littered with ub 
https://github.com/KhronosGroup/glslang/issues/2459

**Comment by arcady-lunarg** [comment]
This was fixed by https://github.com/KhronosGroup/glslang/pull/3066 and glslangValidator now refuses to generate SPIR-V which returns images and textures.

**Comment by NBickford-NV** [comment]
Closing per Arcady's comment. Thanks for figuring this out!
